# Generated by Django 4.2.30 on 2026-07-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('voice', 'Voice Note'), ('api', 'API / Validation')], default='whatsapp', max_length=20)),
                ('sender', models.CharField(blank=True, max_length=50)),
                ('raw_input', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=50)),
                ('matched_rule', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('ai_refined', models.BooleanField(default=False)),
                ('response_sent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Conversation Log',
                'verbose_name_plural': 'Conversation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
